name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable  # Menggunakan channel stable
        flutter-version: 3.29.3  # Ganti dengan versi stabil terbaru

    - name: Verify Flutter and Dart Versions
      run: flutter --version && dart --version

    - name: Run flutter pub get
      run: flutter pub get

    - name: Run flutter pub upgrade
      run: flutter pub upgrade
      
    - name: Update Gradle and AGP versions
      run: |
        # Update Gradle version
        sed -i 's/distributionUrl=.*$/distributionUrl=https\\:\/\/services.gradle.org\/distributions\/gradle-8.0-all.zip/' android/gradle/wrapper/gradle-wrapper.properties
        
        # Verify the change
        cat android/gradle/wrapper/gradle-wrapper.properties

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk